#!/bin/bash

rm -vf results/all_tests.csv results/*.csv

for i in results/*.txt
do
    name=`basename -s ".txt" $i`
    echo "${name}" | tee results/$name.csv
    grep real $i | awk '{print $2;}' - >> results/$name.csv 
done

paste results/*.csv > results/all_tests.csv